#!/usr/bin/env python3
"""
train_gru.py — Smart Block Hybrid: GRU over opcode sequences as node features.

Keeps the block-level graph structure (RGCNConv + AttentionalAggregation)
identical to train.py.  Replaces the static 45-feature summary with a GRU
that reads each block's opcode sequence, capturing instruction ORDER within
blocks — the information discarded by the current static feature vector.

Requires: data/{train,valid,test}_graphs.pkl with the block_opcodes key
(generated by the June 2026 preprocess.py run; older pkl files lack it).
No new preprocessing needed.

Architecture:
    per block:  opcode_sequence → Embedding(vocab, 16) → GRU → 32-dim vector
    per graph:  RGCNConv(32→64) → RGCNConv(64→64) → AttentionalAggregation → Linear(1)

Usage:
    python train_gru.py                        # 30 epochs, default hyperparams
    python train_gru.py --epochs 10            # quick sanity check
    python train_gru.py --gru-hidden 64        # larger GRU
    python train_gru.py --hidden 128           # larger GCN
"""

import argparse
import pickle
import sys
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.utils.rnn import pack_padded_sequence
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import RGCNConv
from torch_geometric.nn.aggr import AttentionalAggregation

HERE = Path(__file__).parent
DATA = HERE / "data"


# ---------------------------------------------------------------------------
# Opcode vocabulary
# ---------------------------------------------------------------------------

PAD_IDX = 0
UNK_IDX = 1

_OPCODE_LIST = [
    "alloca", "load", "store", "getelementptr",
    "add", "sub", "mul", "sdiv", "udiv", "srem", "urem",
    "fadd", "fsub", "fmul", "fdiv", "fneg",
    "shl", "lshr", "ashr", "and", "or", "xor",
    "trunc", "zext", "sext", "fptrunc", "fpext",
    "bitcast", "ptrtoint", "inttoptr",
    "br", "ret", "unreachable", "switch",
    "icmp", "fcmp", "call", "phi", "select",
    "extractvalue", "insertvalue", "atomicrmw",
]

VOCAB: dict[str, int] = {"<PAD>": PAD_IDX, "<UNK>": UNK_IDX}
for _i, _opc in enumerate(_OPCODE_LIST, start=2):
    VOCAB[_opc] = _i
VOCAB_SIZE = len(VOCAB)  # 44


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def compute_max_seq_len(pkl_paths: list[Path], cap: int = 128) -> int:
    """Longest per-block opcode sequence across all splits, capped at cap."""
    max_len = 1
    for path in pkl_paths:
        with open(path, "rb") as f:
            raw = pickle.load(f)
        for g in raw:
            for ops in g.get("block_opcodes", []):
                if len(ops) > max_len:
                    max_len = len(ops)
    return min(max_len, cap)


def load_graphs(pkl_path: Path, max_seq_len: int) -> list[Data]:
    with open(pkl_path, "rb") as f:
        raw = pickle.load(f)

    dataset = []
    for g in raw:
        edge_index = torch.tensor(g["edge_index"], dtype=torch.long)
        edge_type  = torch.tensor(g["edge_type"],  dtype=torch.long)
        y          = torch.tensor([g["y"]],        dtype=torch.float)

        block_opcodes = g.get("block_opcodes", [])
        n_blocks = len(block_opcodes)
        if n_blocks == 0:
            continue

        seq_lens:    list[int]       = []
        padded_seqs: list[list[int]] = []
        for ops in block_opcodes:
            indices = [VOCAB.get(opc, UNK_IDX) for opc in ops] if ops else [PAD_IDX]
            length  = min(len(indices), max_seq_len)
            seq_lens.append(max(length, 1))          # pack_padded requires len >= 1
            row = indices[:max_seq_len] + [PAD_IDX] * (max_seq_len - len(indices))
            padded_seqs.append(row[:max_seq_len])

        # opcode_seqs shape: (n_blocks, max_seq_len)
        # PyG treats first dim == num_nodes as a per-node attribute and
        # concatenates correctly across graphs in a batch.
        opcode_seqs = torch.tensor(padded_seqs, dtype=torch.long)
        seq_lens_t  = torch.tensor(seq_lens,    dtype=torch.long)

        # Dummy x so PyG knows the node count; GRU output replaces it in forward().
        x = torch.zeros(n_blocks, 1)

        dataset.append(Data(
            x=x, edge_index=edge_index, edge_type=edge_type, y=y,
            opcode_seqs=opcode_seqs, seq_lens=seq_lens_t,
        ))

    return dataset


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

class DefectGNN_GRU(nn.Module):
    """Block-level PDG with GRU opcode-sequence node embedder.

    Per block: opcode list → Embedding → GRU (last hidden state) → node feature.
    Per graph: RGCNConv × 2 (CFG/DFG) → AttentionalAggregation → classifier.

    The GRU's last hidden state encodes the full opcode sequence of a block,
    preserving instruction order — unlike the static 45-feature summary.
    """

    def __init__(self, vocab_size: int = VOCAB_SIZE,
                 embed_dim: int = 16, gru_hidden: int = 32, hidden: int = 64):
        super().__init__()
        self.emb  = nn.Embedding(vocab_size, embed_dim, padding_idx=PAD_IDX)
        self.gru  = nn.GRU(embed_dim, gru_hidden, batch_first=True)

        self.conv1 = RGCNConv(gru_hidden, hidden, num_relations=2)
        self.conv2 = RGCNConv(hidden,     hidden, num_relations=2)

        gate_nn = nn.Sequential(
            nn.Linear(hidden, hidden // 2),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(hidden // 2, 1),
        )
        self.pool = AttentionalAggregation(gate_nn=gate_nn)
        self.lin  = nn.Linear(hidden, 1)

    def forward(self, opcode_seqs, seq_lens, edge_index, edge_type, batch):
        # opcode_seqs: (total_blocks_in_batch, max_seq_len)
        # seq_lens:    (total_blocks_in_batch,)
        embedded = self.emb(opcode_seqs)                           # (B, L, E)
        packed   = pack_padded_sequence(embedded, seq_lens.cpu(),
                                        batch_first=True, enforce_sorted=False)
        _, hidden = self.gru(packed)                               # (1, B, gru_h)
        x = hidden.squeeze(0)                                      # (B, gru_h)

        x = F.relu(self.conv1(x, edge_index, edge_type))
        x = F.dropout(x, p=0.3, training=self.training)
        x = F.relu(self.conv2(x, edge_index, edge_type))
        x = self.pool(x, batch)
        return self.lin(x).squeeze(-1)


# ---------------------------------------------------------------------------
# Training / evaluation
# ---------------------------------------------------------------------------

def train_epoch(model, loader, optimizer, device, pos_weight=None):
    model.train()
    total_loss = 0.0
    for batch in loader:
        batch = batch.to(device)
        optimizer.zero_grad()
        logits = model(batch.opcode_seqs, batch.seq_lens,
                       batch.edge_index, batch.edge_type, batch.batch)
        loss   = F.binary_cross_entropy_with_logits(
                     logits, batch.y.squeeze(), pos_weight=pos_weight)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * batch.num_graphs
    return total_loss / len(loader.dataset)


@torch.no_grad()
def evaluate(model, loader, device):
    model.eval()
    correct = total = 0
    for batch in loader:
        batch  = batch.to(device)
        logits = model(batch.opcode_seqs, batch.seq_lens,
                       batch.edge_index, batch.edge_type, batch.batch)
        preds  = (logits > 0).long()
        labels = batch.y.squeeze().long()
        correct += (preds == labels).sum().item()
        total   += batch.num_graphs
    return correct / total if total > 0 else 0.0


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--epochs",     type=int,   default=30)
    ap.add_argument("--hidden",     type=int,   default=64,
                    help="GCN hidden dimension")
    ap.add_argument("--gru-hidden", type=int,   default=32,
                    help="GRU hidden dimension (= GCN input dimension)")
    ap.add_argument("--embed-dim",  type=int,   default=16,
                    help="Opcode embedding dimension")
    ap.add_argument("--lr",         type=float, default=1e-3)
    ap.add_argument("--batch-size", type=int,   default=32)
    ap.add_argument("--checkpoint", type=str,   default="model_gru.pt")
    args = ap.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\nDevice: {device}")

    for split in ["train", "valid", "test"]:
        if not (DATA / f"{split}_graphs.pkl").exists():
            print(f"Missing data/{split}_graphs.pkl — run preprocess.py first.")
            sys.exit(1)

    pkl_paths = [DATA / f"{split}_graphs.pkl" for split in ["train", "valid", "test"]]

    print("Computing max opcode sequence length (cap=128) ...")
    max_seq_len = compute_max_seq_len(pkl_paths, cap=128)
    print(f"  max_seq_len = {max_seq_len}")

    print("Loading graphs ...")
    train_data = load_graphs(DATA / "train_graphs.pkl", max_seq_len)
    valid_data = load_graphs(DATA / "valid_graphs.pkl", max_seq_len)
    test_data  = load_graphs(DATA / "test_graphs.pkl",  max_seq_len)
    print(f"  train={len(train_data)}  valid={len(valid_data)}  test={len(test_data)}")

    vuln_train  = sum(1 for d in train_data if d.y.item() == 1)
    fixed_train = len(train_data) - vuln_train
    pos_weight  = torch.tensor([fixed_train / vuln_train]).to(device)
    print(f"  train class balance: {vuln_train} vuln / {fixed_train} fixed")
    print(f"  pos_weight: {pos_weight.item():.3f}\n")

    train_loader = DataLoader(train_data, batch_size=args.batch_size, shuffle=True)
    valid_loader = DataLoader(valid_data, batch_size=args.batch_size)
    test_loader  = DataLoader(test_data,  batch_size=args.batch_size)

    model = DefectGNN_GRU(
        vocab_size  = VOCAB_SIZE,
        embed_dim   = args.embed_dim,
        gru_hidden  = args.gru_hidden,
        hidden      = args.hidden,
    ).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.5)

    n_params = sum(p.numel() for p in model.parameters())
    print(f"Model: DefectGNN-GRU(vocab={VOCAB_SIZE}, emb={args.embed_dim}, "
          f"gru_h={args.gru_hidden}, gcn_h={args.hidden})  params={n_params:,}\n")

    best_val_acc = 0.0
    checkpoint   = Path(args.checkpoint)

    print(f"{'Epoch':>5}  {'Loss':>8}  {'Val Acc':>8}  {'':>6}")
    print("-" * 35)

    for epoch in range(1, args.epochs + 1):
        loss    = train_epoch(model, train_loader, optimizer, device, pos_weight)
        val_acc = evaluate(model, valid_loader, device)
        scheduler.step()

        marker = ""
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            torch.save(model.state_dict(), checkpoint)
            marker = "← best"

        print(f"{epoch:>5}  {loss:>8.4f}  {val_acc:>8.2%}  {marker}")

    print(f"\nLoading best checkpoint ({checkpoint}) ...")
    model.load_state_dict(torch.load(checkpoint, map_location=device))
    test_acc = evaluate(model, test_loader, device)
    print(f"Test accuracy: {test_acc:.2%}")
    print(f"Checkpoint saved to: {checkpoint.resolve()}\n")

    print("--- Comparison ---")
    print(f"  Block-level GNN, 45-feat static (4d best):   57.84%")
    print(f"  Instruction-level GNN, one-hot (5a):          55.84%")
    print(f"  GRU hybrid — opcode sequences (this run):     {test_acc:.2%}")
    print(f"  CodeBERT (4a):                                63.43%")

    if test_acc >= 0.60:
        print("✓ Opcode order carries real signal — GRU hybrid closes most of the gap")
    elif test_acc > 0.5784:
        print("— Marginal improvement; sequence order helps but gap remains")
    else:
        print("— No improvement; within-block order is not load-bearing on this dataset")


if __name__ == "__main__":
    main()
