#!/usr/bin/env python3
"""
train_codebert.py — Fine-tune CodeBERT on Devign for defect detection.

Uses the same train/valid/test JSONL splits as train.py (generated by
preprocess.py).  Reads raw C source code — no compilation needed.

Published baseline: CodeBERT 62%, UniXcoder 69% on Devign.

Usage:
    python train_codebert.py                     # full dataset, 5 epochs
    python train_codebert.py --epochs 3          # faster run
    python train_codebert.py --max-len 256       # shorter sequences (2x faster on CPU)
    python train_codebert.py --max-samples 500   # sanity-check subset
    python train_codebert.py --batch-size 8      # reduce if OOM
"""

import argparse
import json
from pathlib import Path

import torch
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    get_linear_schedule_with_warmup,
)

HERE = Path(__file__).parent
DATA = HERE / "data"

MODEL_NAME = "microsoft/codebert-base"


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class DevignDataset(Dataset):
    def __init__(self, jsonl_path: Path, tokenizer, max_len: int,
                 max_samples: int | None = None):
        self.samples = []
        with open(jsonl_path) as f:
            for i, line in enumerate(f):
                if max_samples and i >= max_samples:
                    break
                obj = json.loads(line)
                self.samples.append((obj["func"], int(obj["target"])))
        self.tokenizer = tokenizer
        self.max_len   = max_len

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        code, label = self.samples[idx]
        enc = self.tokenizer(
            code,
            max_length=self.max_len,
            truncation=True,
            padding="max_length",
            return_tensors="pt",
        )
        return {
            "input_ids":      enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "label":          torch.tensor(label, dtype=torch.long),
        }


# ---------------------------------------------------------------------------
# Training / evaluation
# ---------------------------------------------------------------------------

def train_epoch(model, loader, optimizer, scheduler, device):
    model.train()
    total_loss = 0.0
    for batch in loader:
        input_ids      = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels         = batch["label"].to(device)

        optimizer.zero_grad()
        out  = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = out.loss
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()
        total_loss += loss.item() * input_ids.size(0)

    return total_loss / len(loader.dataset)


@torch.no_grad()
def evaluate(model, loader, device):
    model.eval()
    correct = total = 0
    for batch in loader:
        input_ids      = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels         = batch["label"].to(device)

        logits = model(input_ids=input_ids, attention_mask=attention_mask).logits
        preds  = logits.argmax(dim=-1)
        correct += (preds == labels).sum().item()
        total   += labels.size(0)

    return correct / total if total > 0 else 0.0


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--epochs",      type=int,   default=5)
    ap.add_argument("--batch-size",  type=int,   default=16)
    ap.add_argument("--max-len",     type=int,   default=512,
                    help="Token sequence length. 256 is ~2x faster on CPU.")
    ap.add_argument("--lr",          type=float, default=2e-5)
    ap.add_argument("--max-samples", type=int,   default=None,
                    help="Cap each split (quick sanity check)")
    ap.add_argument("--checkpoint",  type=str,   default="codebert_model.pt")
    args = ap.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\nDevice: {device}")
    if device.type == "cpu":
        print("Note: CPU training is slow. --max-len 256 halves runtime. "
              "--max-samples 500 for a quick sanity check.\n")

    for split in ["train", "valid", "test"]:
        if not (DATA / f"{split}.jsonl").exists():
            print(f"Missing data/{split}.jsonl — run preprocess.py first.")
            raise SystemExit(1)

    print(f"Loading tokenizer: {MODEL_NAME} ...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

    print("Building datasets ...")
    train_ds = DevignDataset(DATA / "train.jsonl", tokenizer, args.max_len, args.max_samples)
    valid_ds = DevignDataset(DATA / "valid.jsonl", tokenizer, args.max_len,
                             args.max_samples // 8 if args.max_samples else None)
    test_ds  = DevignDataset(DATA / "test.jsonl",  tokenizer, args.max_len,
                             args.max_samples // 8 if args.max_samples else None)

    print(f"  train={len(train_ds)}  valid={len(valid_ds)}  test={len(test_ds)}")

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True)
    valid_loader = DataLoader(valid_ds, batch_size=args.batch_size)
    test_loader  = DataLoader(test_ds,  batch_size=args.batch_size)

    print(f"\nLoading model: {MODEL_NAME} ...")
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME, num_labels=2
    ).to(device)

    n_params = sum(p.numel() for p in model.parameters())
    print(f"Model params: {n_params:,}  (vs GNN: ~21K–67K)\n")

    optimizer = AdamW(model.parameters(), lr=args.lr, weight_decay=0.01)
    total_steps = len(train_loader) * args.epochs
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=total_steps // 10,
        num_training_steps=total_steps,
    )

    best_val_acc = 0.0
    checkpoint   = Path(args.checkpoint)

    print(f"{'Epoch':>5}  {'Loss':>8}  {'Val Acc':>8}  {'':>6}")
    print("-" * 35)

    for epoch in range(1, args.epochs + 1):
        loss    = train_epoch(model, train_loader, optimizer, scheduler, device)
        val_acc = evaluate(model, valid_loader, device)

        marker = ""
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            torch.save(model.state_dict(), checkpoint)
            marker = "← best"

        print(f"{epoch:>5}  {loss:>8.4f}  {val_acc:>8.2%}  {marker}")

    print(f"\nLoading best checkpoint ({checkpoint}) ...")
    model.load_state_dict(torch.load(checkpoint, map_location=device))
    test_acc = evaluate(model, test_loader, device)
    print(f"Test accuracy: {test_acc:.2%}")
    print(f"Checkpoint saved to: {checkpoint.resolve()}\n")

    if test_acc >= 0.62:
        print("✓ Matches or exceeds published CodeBERT baseline (62%)")
    elif test_acc >= 0.55:
        print("— Below published baseline; try more epochs or full sequence length")
    else:
        print("✗ Accuracy low — check data or increase epochs")

    print(f"\n--- Summary vs GNN ---")
    print(f"  GNN  (PDG + 45 features, basic-block):  ~57%")
    print(f"  CodeBERT (raw source, published):        ~62%")
    print(f"  CodeBERT (this run):                     {test_acc:.2%}")


if __name__ == "__main__":
    main()
